# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetWalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KakaoSDKUser'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'Alamofire', '~> 5.4'
  pod 'SideMenu'
  pod 'FSCalendar'

  # Pods for PetWalk

end
